Repository Eranziel/foundryvtt-lancer, pull requests merged in 2025-02, with the labels that each got.

#803 Fix consuming lockon
  src/module/flows/attack.ts
  src/module/flows/damage.ts
  src/module/flows/tech.ts
Labels: automation

#808 Use downandout as the defeated status
  src/module/effects/lancer-active-effect.ts
Labels: automation

#815 Use OVERRIDE for cheap_struct and cheap_stress
  src/module/effects/converter.ts
Labels: automation, models

#810 Add option to attack roll dialog for flat bonus to the attack
  src/module/apps/acc_diff/AccDiffHUD.svelte
  src/module/config.ts
  src/module/flows/attack.ts
  src/module/settings.ts
Labels: feature
